
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	private global::Gtk.HBox hbox2;
	private global::Gtk.VBox vbox6;
	private global::Gtk.Label label_architectur;
	private global::Gtk.VBox vbox4;
	private global::Gtk.ComboBox computer;
	private global::Gtk.ComboBox platform;
	private global::Gtk.VBox vbox5;
	private global::Gtk.Button b_dl_master;
	private global::Gtk.HBox hbox3;
	private global::Gtk.Label l_dlfolder;
	private global::Gtk.FileChooserButton f_dlChoose;
	private global::Gtk.ProgressBar dl_progress;
	private global::Gtk.VBox vbox9;
	private global::Gtk.HBox hbox5;
	private global::Gtk.Label l_main;
	private global::Gtk.FileChooserButton filechooserbutton3;
	private global::Gtk.Button b_delete1;
	private global::Gtk.HBox hbox6;
	private global::Gtk.Label l_help;
	private global::Gtk.FileChooserButton filechooserbutton4;
	private global::Gtk.Button b_delete2;
	private global::Gtk.HBox hbox7;
	private global::Gtk.Button b_startDL;
	private global::Gtk.Label l_dlfolder1;
	private global::Gtk.FileChooserButton f_installation_choose;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("LibreOffice Server Install GUI LE");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(5));
		this.Resizable = false;
		this.AllowGrow = false;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.vbox6 = new global::Gtk.VBox ();
		this.vbox6.Name = "vbox6";
		this.vbox6.Spacing = 6;
		// Container child vbox6.Gtk.Box+BoxChild
		this.label_architectur = new global::Gtk.Label ();
		this.label_architectur.WidthRequest = 100;
		this.label_architectur.HeightRequest = 62;
		this.label_architectur.Name = "label_architectur";
		this.label_architectur.LabelProp = global::Mono.Unix.Catalog.GetString ("Architectur");
		this.vbox6.Add (this.label_architectur);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.label_architectur]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		this.hbox2.Add (this.vbox6);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox6]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.computer = global::Gtk.ComboBox.NewText ();
		this.computer.AppendText (global::Mono.Unix.Catalog.GetString ("x86"));
		this.computer.AppendText (global::Mono.Unix.Catalog.GetString ("x86_64"));
		this.computer.WidthRequest = 80;
		this.computer.Name = "computer";
		this.computer.Active = 0;
		this.vbox4.Add (this.computer);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.computer]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.platform = global::Gtk.ComboBox.NewText ();
		this.platform.AppendText (global::Mono.Unix.Catalog.GetString ("deb"));
		this.platform.AppendText (global::Mono.Unix.Catalog.GetString ("rpm"));
		this.platform.WidthRequest = 80;
		this.platform.Name = "platform";
		this.platform.Active = 1;
		this.vbox4.Add (this.platform);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.platform]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		this.hbox2.Add (this.vbox4);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox4]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.vbox5 = new global::Gtk.VBox ();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.b_dl_master = new global::Gtk.Button ();
		this.b_dl_master.CanFocus = true;
		this.b_dl_master.Name = "b_dl_master";
		this.b_dl_master.UseUnderline = true;
		this.b_dl_master.Label = global::Mono.Unix.Catalog.GetString ("Download master");
		this.vbox5.Add (this.b_dl_master);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.b_dl_master]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.l_dlfolder = new global::Gtk.Label ();
		this.l_dlfolder.Name = "l_dlfolder";
		this.l_dlfolder.LabelProp = global::Mono.Unix.Catalog.GetString ("Choose folder");
		this.hbox3.Add (this.l_dlfolder);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.l_dlfolder]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.f_dlChoose = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Choose folder"), ((global::Gtk.FileChooserAction)(2)));
		this.f_dlChoose.Name = "f_dlChoose";
		this.hbox3.Add (this.f_dlChoose);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.f_dlChoose]));
		w8.Position = 1;
		this.vbox5.Add (this.hbox3);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox3]));
		w9.Position = 1;
		w9.Expand = false;
		w9.Fill = false;
		this.hbox2.Add (this.vbox5);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox5]));
		w10.Position = 2;
		this.vbox1.Add (this.hbox2);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
		w11.Position = 0;
		w11.Expand = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.dl_progress = new global::Gtk.ProgressBar ();
		this.dl_progress.Name = "dl_progress";
		this.dl_progress.Text = global::Mono.Unix.Catalog.GetString ("Download Progress");
		this.vbox1.Add (this.dl_progress);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.dl_progress]));
		w12.Position = 1;
		w12.Expand = false;
		w12.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox9 = new global::Gtk.VBox ();
		this.vbox9.Name = "vbox9";
		this.vbox9.Spacing = 6;
		// Container child vbox9.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox ();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.l_main = new global::Gtk.Label ();
		this.l_main.WidthRequest = 200;
		this.l_main.Name = "l_main";
		this.l_main.LabelProp = global::Mono.Unix.Catalog.GetString ("LibreOffice Main installer");
		this.hbox5.Add (this.l_main);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.l_main]));
		w13.Position = 0;
		w13.Expand = false;
		w13.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.filechooserbutton3 = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Datei auswählen"), ((global::Gtk.FileChooserAction)(0)));
		this.filechooserbutton3.Name = "filechooserbutton3";
		this.hbox5.Add (this.filechooserbutton3);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.filechooserbutton3]));
		w14.Position = 1;
		// Container child hbox5.Gtk.Box+BoxChild
		this.b_delete1 = new global::Gtk.Button ();
		this.b_delete1.CanFocus = true;
		this.b_delete1.Name = "b_delete1";
		this.b_delete1.UseUnderline = true;
		this.b_delete1.Label = "X";
		this.hbox5.Add (this.b_delete1);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.b_delete1]));
		w15.Position = 2;
		w15.Expand = false;
		w15.Fill = false;
		this.vbox9.Add (this.hbox5);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.hbox5]));
		w16.Position = 0;
		w16.Expand = false;
		w16.Fill = false;
		// Container child vbox9.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox ();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.l_help = new global::Gtk.Label ();
		this.l_help.WidthRequest = 200;
		this.l_help.Name = "l_help";
		this.l_help.LabelProp = global::Mono.Unix.Catalog.GetString ("LibreOffice Helppack");
		this.hbox6.Add (this.l_help);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.l_help]));
		w17.Position = 0;
		w17.Expand = false;
		w17.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.filechooserbutton4 = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Datei auswählen"), ((global::Gtk.FileChooserAction)(0)));
		this.filechooserbutton4.Name = "filechooserbutton4";
		this.hbox6.Add (this.filechooserbutton4);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.filechooserbutton4]));
		w18.Position = 1;
		// Container child hbox6.Gtk.Box+BoxChild
		this.b_delete2 = new global::Gtk.Button ();
		this.b_delete2.CanFocus = true;
		this.b_delete2.Name = "b_delete2";
		this.b_delete2.UseUnderline = true;
		this.b_delete2.Label = "X";
		this.hbox6.Add (this.b_delete2);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.b_delete2]));
		w19.Position = 2;
		w19.Expand = false;
		w19.Fill = false;
		this.vbox9.Add (this.hbox6);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.hbox6]));
		w20.Position = 1;
		w20.Expand = false;
		w20.Fill = false;
		this.vbox1.Add (this.vbox9);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox9]));
		w21.Position = 2;
		w21.Expand = false;
		w21.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox ();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.b_startDL = new global::Gtk.Button ();
		this.b_startDL.CanFocus = true;
		this.b_startDL.Name = "b_startDL";
		this.b_startDL.UseUnderline = true;
		this.b_startDL.Label = global::Mono.Unix.Catalog.GetString ("Start parallel installation");
		this.hbox7.Add (this.b_startDL);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.b_startDL]));
		w22.Position = 0;
		w22.Expand = false;
		w22.Fill = false;
		// Container child hbox7.Gtk.Box+BoxChild
		this.l_dlfolder1 = new global::Gtk.Label ();
		this.l_dlfolder1.Name = "l_dlfolder1";
		this.l_dlfolder1.LabelProp = global::Mono.Unix.Catalog.GetString ("Choose folder");
		this.hbox7.Add (this.l_dlfolder1);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.l_dlfolder1]));
		w23.Position = 1;
		w23.Expand = false;
		w23.Fill = false;
		// Container child hbox7.Gtk.Box+BoxChild
		this.f_installation_choose = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Datei auswählen"), ((global::Gtk.FileChooserAction)(2)));
		this.f_installation_choose.Name = "f_installation_choose";
		this.hbox7.Add (this.f_installation_choose);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.f_installation_choose]));
		w24.Position = 2;
		this.vbox1.Add (this.hbox7);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox7]));
		w25.Position = 3;
		w25.Expand = false;
		w25.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 494;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.b_dl_master.Pressed += new global::System.EventHandler (this.start_dl_master);
	}
}
