//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApplication1.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        internal static string abort {
            get {
                return ResourceManager.GetString("abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About / Change language.
        /// </summary>
        internal static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All LibO versions.
        /// </summary>
        internal static string any_libo_version {
            get {
                return ResourceManager.GetString("any_libo_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Shortcut.
        /// </summary>
        internal static string b_create_shortcut {
            get {
                return ResourceManager.GetString("b_create_shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure installation directory.
        /// </summary>
        internal static string config_installdir {
            get {
                return ResourceManager.GetString("config_installdir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danish:.
        /// </summary>
        internal static string da {
            get {
                return ResourceManager.GetString("da", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German:.
        /// </summary>
        internal static string de {
            get {
                return ResourceManager.GetString("de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory does not exist!.
        /// </summary>
        internal static string dirnotfound {
            get {
                return ResourceManager.GetString("dirnotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your choosen directory!.
        /// </summary>
        internal static string dirnotfoundmessage {
            get {
                return ResourceManager.GetString("dirnotfoundmessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The download has been finished and is ready for installation..
        /// </summary>
        internal static string dl_finished {
            get {
                return ResourceManager.GetString("dl_finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download finished!.
        /// </summary>
        internal static string dl_finished_title {
            get {
                return ResourceManager.GetString("dl_finished_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A download has been started!.
        /// </summary>
        internal static string dl_started {
            get {
                return ResourceManager.GetString("dl_started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download started!.
        /// </summary>
        internal static string dl_started_title {
            get {
                return ResourceManager.GetString("dl_started_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit bootstrap.ini.
        /// </summary>
        internal static string edit_bs_ini {
            get {
                return ResourceManager.GetString("edit_bs_ini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English:.
        /// </summary>
        internal static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to choose a language before starting the download!.
        /// </summary>
        internal static string error_langpack_nolang {
            get {
                return ResourceManager.GetString("error_langpack_nolang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish:.
        /// </summary>
        internal static string es {
            get {
                return ResourceManager.GetString("es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file has successfully been saved!.
        /// </summary>
        internal static string filesave {
            get {
                return ResourceManager.GetString("filesave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French:.
        /// </summary>
        internal static string fr {
            get {
                return ResourceManager.GetString("fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin download.
        /// </summary>
        internal static string gb_dl_begindl {
            get {
                return ResourceManager.GetString("gb_dl_begindl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline help.
        /// </summary>
        internal static string gb_dl_help {
            get {
                return ResourceManager.GetString("gb_dl_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installer.
        /// </summary>
        internal static string gb_dl_installer {
            get {
                return ResourceManager.GetString("gb_dl_installer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update list of versions.
        /// </summary>
        internal static string gb_dl_update {
            get {
                return ResourceManager.GetString("gb_dl_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parallel installation.
        /// </summary>
        internal static string gb_parallel_install {
            get {
                return ResourceManager.GetString("gb_parallel_install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back?.
        /// </summary>
        internal static string go_back {
            get {
                return ResourceManager.GetString("go_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hebrew:.
        /// </summary>
        internal static string he {
            get {
                return ResourceManager.GetString("he", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It might help to run this program as administrator..
        /// </summary>
        internal static string help_runasadmin {
            get {
                return ResourceManager.GetString("help_runasadmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut to a parallel installed LibreOffice %version..
        /// </summary>
        internal static string ink_des {
            get {
                return ResourceManager.GetString("ink_des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No version specified!.
        /// </summary>
        internal static string ink_error_1 {
            get {
                return ResourceManager.GetString("ink_error_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation could not be startet due to the following error:.
        /// </summary>
        internal static string installerror {
            get {
                return ResourceManager.GetString("installerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation could not be started!.
        /// </summary>
        internal static string installnostart {
            get {
                return ResourceManager.GetString("installnostart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string lang {
            get {
                return ResourceManager.GetString("lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language setting will apply at the next startup!.
        /// </summary>
        internal static string language_change_success {
            get {
                return ResourceManager.GetString("language_change_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Download.
        /// </summary>
        internal static string m_l10n_dl {
            get {
                return ResourceManager.GetString("m_l10n_dl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Helppack.
        /// </summary>
        internal static string m_l10n_helppack {
            get {
                return ResourceManager.GetString("m_l10n_helppack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Installer.
        /// </summary>
        internal static string m_l10n_installer {
            get {
                return ResourceManager.GetString("m_l10n_installer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language (help):.
        /// </summary>
        internal static string m_l10n_langhelptxt {
            get {
                return ResourceManager.GetString("m_l10n_langhelptxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Latest branch.
        /// </summary>
        internal static string m_l10n_lb {
            get {
                return ResourceManager.GetString("m_l10n_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Older branch.
        /// </summary>
        internal static string m_l10n_ob {
            get {
                return ResourceManager.GetString("m_l10n_ob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Testing build.
        /// </summary>
        internal static string m_l10n_t {
            get {
                return ResourceManager.GetString("m_l10n_t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        internal static string mai_abort {
            get {
                return ResourceManager.GetString("mai_abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure path.
        /// </summary>
        internal static string mai_config_path {
            get {
                return ResourceManager.GetString("mai_config_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay.
        /// </summary>
        internal static string mai_ok {
            get {
                return ResourceManager.GetString("mai_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to the soffice.exe of the parallel installation.
        /// </summary>
        internal static string mai_path_soffice {
            get {
                return ResourceManager.GetString("mai_path_soffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manually add parallel installation.
        /// </summary>
        internal static string mai_text {
            get {
                return ResourceManager.GetString("mai_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manually add installation.
        /// </summary>
        internal static string man_addinstall {
            get {
                return ResourceManager.GetString("man_addinstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected.
        /// </summary>
        internal static string man_del {
            get {
                return ResourceManager.GetString("man_del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string man_exit {
            get {
                return ResourceManager.GetString("man_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        internal static string man_title {
            get {
                return ResourceManager.GetString("man_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download has been aborted!.
        /// </summary>
        internal static string massdl_error {
            get {
                return ResourceManager.GetString("massdl_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download any version of %product !.
        /// </summary>
        internal static string massdl_l10n_title {
            get {
                return ResourceManager.GetString("massdl_l10n_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which version should be downloaded?.
        /// </summary>
        internal static string massdl_l10n_which {
            get {
                return ResourceManager.GetString("massdl_l10n_which", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut created!.
        /// </summary>
        internal static string msb_lnk_title {
            get {
                return ResourceManager.GetString("msb_lnk_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut has sucessfully been created!.
        /// </summary>
        internal static string msb_lnk_txt {
            get {
                return ResourceManager.GetString("msb_lnk_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dutch:.
        /// </summary>
        internal static string nl {
            get {
                return ResourceManager.GetString("nl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No install directory choosen!.
        /// </summary>
        internal static string no_installdir {
            get {
                return ResourceManager.GetString("no_installdir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You did not choose a LibreOffice Installation file!.
        /// </summary>
        internal static string no_installfile {
            get {
                return ResourceManager.GetString("no_installfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.EXE files are not supported for installation!.
        /// </summary>
        internal static string no_valid_filename_error_text {
            get {
                return ResourceManager.GetString("no_valid_filename_error_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not supported!.
        /// </summary>
        internal static string no_valid_filename_error_title {
            get {
                return ResourceManager.GetString("no_valid_filename_error_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No test version!.
        /// </summary>
        internal static string notest_ti {
            get {
                return ResourceManager.GetString("notest_ti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No testversion available at the moment..
        /// </summary>
        internal static string notest_txt {
            get {
                return ResourceManager.GetString("notest_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay.
        /// </summary>
        internal static string okay {
            get {
                return ResourceManager.GetString("okay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open bootstrap.ini.
        /// </summary>
        internal static string open_bootstrap_ini {
            get {
                return ResourceManager.GetString("open_bootstrap_ini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open bootstrap.ini.
        /// </summary>
        internal static string open_bootstrap_title {
            get {
                return ResourceManager.GetString("open_bootstrap_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open LibreOffice help installer.
        /// </summary>
        internal static string open_help {
            get {
                return ResourceManager.GetString("open_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open LibreOffice installer.
        /// </summary>
        internal static string open_installer {
            get {
                return ResourceManager.GetString("open_installer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programmer:.
        /// </summary>
        internal static string programmer {
            get {
                return ResourceManager.GetString("programmer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress:.
        /// </summary>
        internal static string progress {
            get {
                return ResourceManager.GetString("progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese:.
        /// </summary>
        internal static string pt {
            get {
                return ResourceManager.GetString("pt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        internal static string s_and {
            get {
                return ResourceManager.GetString("s_and", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        internal static string s_version {
            get {
                return ResourceManager.GetString("s_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save bootstrap.ini.
        /// </summary>
        internal static string save_bootstrap_ini {
            get {
                return ResourceManager.GetString("save_bootstrap_ini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Issue.
        /// </summary>
        internal static string si {
            get {
                return ResourceManager.GetString("si", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have the right to write into this folder..
        /// </summary>
        internal static string si_message {
            get {
                return ResourceManager.GetString("si_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovenian:.
        /// </summary>
        internal static string sl {
            get {
                return ResourceManager.GetString("sl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occoured! Message:.
        /// </summary>
        internal static string standarderror {
            get {
                return ResourceManager.GetString("standarderror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start download.
        /// </summary>
        internal static string start_dl {
            get {
                return ResourceManager.GetString("start_dl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start installation.
        /// </summary>
        internal static string start_install {
            get {
                return ResourceManager.GetString("start_install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should the file be downloaded?.
        /// </summary>
        internal static string startdl {
            get {
                return ResourceManager.GetString("startdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should a subfolder be created automatically? Name of the subfolder:.
        /// </summary>
        internal static string subfolder_do {
            get {
                return ResourceManager.GetString("subfolder_do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        internal static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File saved.
        /// </summary>
        internal static string title_filesave {
            get {
                return ResourceManager.GetString("title_filesave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- Translations ---.
        /// </summary>
        internal static string translations {
            get {
                return ResourceManager.GetString("translations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translator:.
        /// </summary>
        internal static string translator {
            get {
                return ResourceManager.GetString("translator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may use the following instead of the line starting with “UserInstallation=” from the text field above in order to not override your existing user profile..
        /// </summary>
        internal static string tt_bootstrap {
            get {
                return ResourceManager.GetString("tt_bootstrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a desktop shortcut for this parallel installation.
        /// </summary>
        internal static string tt_ink {
            get {
                return ResourceManager.GetString("tt_ink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to the soffice.exe of the parallel installation (Automatically added).
        /// </summary>
        internal static string tt_path_to_exe {
            get {
                return ResourceManager.GetString("tt_path_to_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language:.
        /// </summary>
        internal static string update_lang {
            get {
                return ResourceManager.GetString("update_lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should %version really be downloaded?.
        /// </summary>
        internal static string versiondl {
            get {
                return ResourceManager.GetString("versiondl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        internal static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose installation directory.
        /// </summary>
        internal static string where_to_install {
            get {
                return ResourceManager.GetString("where_to_install", resourceCulture);
            }
        }
    }
}
