//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SI_GUI.l10n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SI_GUI.l10n.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About / Settings.
        /// </summary>
        internal static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All LibO versions.
        /// </summary>
        internal static string any_libo_version {
            get {
                return ResourceManager.GetString("any_libo_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Shortcut.
        /// </summary>
        internal static string b_create_shortcut {
            get {
                return ResourceManager.GetString("b_create_shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back.
        /// </summary>
        internal static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced file renaming.
        /// </summary>
        internal static string cb_advanced_file {
            get {
                return ResourceManager.GetString("cb_advanced_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-edit bootstrap.ini.
        /// </summary>
        internal static string cb_autoedit {
            get {
                return ResourceManager.GetString("cb_autoedit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure installation directory.
        /// </summary>
        internal static string config_installdir {
            get {
                return ResourceManager.GetString("config_installdir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should the folder %folder% be created automatically?.
        /// </summary>
        internal static string createdir {
            get {
                return ResourceManager.GetString("createdir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danish.
        /// </summary>
        internal static string da {
            get {
                return ResourceManager.GetString("da", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        internal static string de {
            get {
                return ResourceManager.GetString("de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong URL. Retry please..
        /// </summary>
        internal static string dia_wrongURL {
            get {
                return ResourceManager.GetString("dia_wrongURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory does not exist!.
        /// </summary>
        internal static string dirnotfound {
            get {
                return ResourceManager.GetString("dirnotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your chosen directory!.
        /// </summary>
        internal static string dirnotfoundmessage {
            get {
                return ResourceManager.GetString("dirnotfoundmessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The download has been finished and is ready for installation..
        /// </summary>
        internal static string dl_finished {
            get {
                return ResourceManager.GetString("dl_finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download finished!.
        /// </summary>
        internal static string dl_finished_title {
            get {
                return ResourceManager.GetString("dl_finished_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A download has been started!.
        /// </summary>
        internal static string dl_started {
            get {
                return ResourceManager.GetString("dl_started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download started!.
        /// </summary>
        internal static string dl_started_title {
            get {
                return ResourceManager.GetString("dl_started_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start download and installing.
        /// </summary>
        internal static string dla_button {
            get {
                return ResourceManager.GetString("dla_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL:.
        /// </summary>
        internal static string dla_label {
            get {
                return ResourceManager.GetString("dla_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download anything.
        /// </summary>
        internal static string dla_tit {
            get {
                return ResourceManager.GetString("dla_tit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit bootstrap.ini.
        /// </summary>
        internal static string edit_bs_ini {
            get {
                return ResourceManager.GetString("edit_bs_ini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to choose a language before starting the download!.
        /// </summary>
        internal static string error_langpack_nolang {
            get {
                return ResourceManager.GetString("error_langpack_nolang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        internal static string es {
            get {
                return ResourceManager.GetString("es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file has successfully been saved!.
        /// </summary>
        internal static string filesave {
            get {
                return ResourceManager.GetString("filesave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        internal static string fr {
            get {
                return ResourceManager.GetString("fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear user,nlThis program uses &quot;TDF Piwik&quot;  in order to get statistics about the usage of this program.nlWe have created a tracking ID for this installation. Your tracking ID isnl%trackingIDnlAs you can see, this does not contain any private information. Press&quot;Yes&quot; in order to allow tracking, &quot;No&quot; in order to prohibit..
        /// </summary>
        internal static string ga_allowed_text {
            get {
                return ResourceManager.GetString("ga_allowed_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics powered by &quot;TDF Piwik&quot; ..
        /// </summary>
        internal static string ga_allowed_title {
            get {
                return ResourceManager.GetString("ga_allowed_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow tracking your usage of the program with help of &quot;TDF Piwik&quot;.
        /// </summary>
        internal static string ga_cb_allowed {
            get {
                return ResourceManager.GetString("ga_cb_allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin download.
        /// </summary>
        internal static string gb_dl_begindl {
            get {
                return ResourceManager.GetString("gb_dl_begindl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline help.
        /// </summary>
        internal static string gb_dl_help {
            get {
                return ResourceManager.GetString("gb_dl_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installer.
        /// </summary>
        internal static string gb_dl_installer {
            get {
                return ResourceManager.GetString("gb_dl_installer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update list of versions.
        /// </summary>
        internal static string gb_dl_update {
            get {
                return ResourceManager.GetString("gb_dl_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parallel installation.
        /// </summary>
        internal static string gb_parallel_install {
            get {
                return ResourceManager.GetString("gb_parallel_install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galician.
        /// </summary>
        internal static string gl {
            get {
                return ResourceManager.GetString("gl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back?.
        /// </summary>
        internal static string go_back {
            get {
                return ResourceManager.GetString("go_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hebrew.
        /// </summary>
        internal static string he {
            get {
                return ResourceManager.GetString("he", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It might help to run this program as administrator..
        /// </summary>
        internal static string help_runasadmin {
            get {
                return ResourceManager.GetString("help_runasadmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut to a parallel installed LibreOffice %version..
        /// </summary>
        internal static string ink_des {
            get {
                return ResourceManager.GetString("ink_des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No version specified!.
        /// </summary>
        internal static string ink_error_1 {
            get {
                return ResourceManager.GetString("ink_error_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No path to soffice.exe could be detected!.
        /// </summary>
        internal static string ink_error_2 {
            get {
                return ResourceManager.GetString("ink_error_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwriting existing Server Installation!.
        /// </summary>
        internal static string install_err1_tit {
            get {
                return ResourceManager.GetString("install_err1_tit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to overwrite an existing Server Installation. Continue?.
        /// </summary>
        internal static string install_err1_txt {
            get {
                return ResourceManager.GetString("install_err1_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation could not be started due to the following error.
        /// </summary>
        internal static string installerror {
            get {
                return ResourceManager.GetString("installerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation could not be started!.
        /// </summary>
        internal static string installnostart {
            get {
                return ResourceManager.GetString("installnostart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian.
        /// </summary>
        internal static string it {
            get {
                return ResourceManager.GetString("it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string lang {
            get {
                return ResourceManager.GetString("lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language setting will apply at the next startup!.
        /// </summary>
        internal static string language_change_success {
            get {
                return ResourceManager.GetString("language_change_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lao.
        /// </summary>
        internal static string lo {
            get {
                return ResourceManager.GetString("lo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string m_l10n_dl {
            get {
                return ResourceManager.GetString("m_l10n_dl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help pack.
        /// </summary>
        internal static string m_l10n_helppack {
            get {
                return ResourceManager.GetString("m_l10n_helppack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installer.
        /// </summary>
        internal static string m_l10n_installer {
            get {
                return ResourceManager.GetString("m_l10n_installer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language (help).
        /// </summary>
        internal static string m_l10n_langhelptxt {
            get {
                return ResourceManager.GetString("m_l10n_langhelptxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest branch.
        /// </summary>
        internal static string m_l10n_lb {
            get {
                return ResourceManager.GetString("m_l10n_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Older branch.
        /// </summary>
        internal static string m_l10n_ob {
            get {
                return ResourceManager.GetString("m_l10n_ob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing build.
        /// </summary>
        internal static string m_l10n_t {
            get {
                return ResourceManager.GetString("m_l10n_t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        internal static string mai_abort {
            get {
                return ResourceManager.GetString("mai_abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure path.
        /// </summary>
        internal static string mai_config_path {
            get {
                return ResourceManager.GetString("mai_config_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to the soffice.exe of the parallel installation.
        /// </summary>
        internal static string mai_path_soffice {
            get {
                return ResourceManager.GetString("mai_path_soffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manually add parallel installation.
        /// </summary>
        internal static string mai_text {
            get {
                return ResourceManager.GetString("mai_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manually add installation.
        /// </summary>
        internal static string man_addinstall {
            get {
                return ResourceManager.GetString("man_addinstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected.
        /// </summary>
        internal static string man_del {
            get {
                return ResourceManager.GetString("man_del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string man_exit {
            get {
                return ResourceManager.GetString("man_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        internal static string man_title {
            get {
                return ResourceManager.GetString("man_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut created!.
        /// </summary>
        internal static string msb_lnk_title {
            get {
                return ResourceManager.GetString("msb_lnk_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut has successfully been created!.
        /// </summary>
        internal static string msb_lnk_txt {
            get {
                return ResourceManager.GetString("msb_lnk_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maltese.
        /// </summary>
        internal static string mt {
            get {
                return ResourceManager.GetString("mt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dutch.
        /// </summary>
        internal static string nl {
            get {
                return ResourceManager.GetString("nl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No install directory chosen!.
        /// </summary>
        internal static string no_installdir {
            get {
                return ResourceManager.GetString("no_installdir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You did not choose a LibreOffice Installation file!.
        /// </summary>
        internal static string no_installfile {
            get {
                return ResourceManager.GetString("no_installfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No test version!.
        /// </summary>
        internal static string notest_ti {
            get {
                return ResourceManager.GetString("notest_ti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No test version available at the moment..
        /// </summary>
        internal static string notest_txt {
            get {
                return ResourceManager.GetString("notest_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay.
        /// </summary>
        internal static string okay {
            get {
                return ResourceManager.GetString("okay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open bootstrap.ini.
        /// </summary>
        internal static string open_bootstrap_ini {
            get {
                return ResourceManager.GetString("open_bootstrap_ini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open bootstrap.ini.
        /// </summary>
        internal static string open_bootstrap_title {
            get {
                return ResourceManager.GetString("open_bootstrap_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open LibreOffice help installer.
        /// </summary>
        internal static string open_help {
            get {
                return ResourceManager.GetString("open_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open LibreOffice installer.
        /// </summary>
        internal static string open_installer {
            get {
                return ResourceManager.GetString("open_installer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programmer.
        /// </summary>
        internal static string programmer {
            get {
                return ResourceManager.GetString("programmer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        internal static string progress {
            get {
                return ResourceManager.GetString("progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese.
        /// </summary>
        internal static string pt {
            get {
                return ResourceManager.GetString("pt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        internal static string s_and {
            get {
                return ResourceManager.GetString("s_and", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string s_version {
            get {
                return ResourceManager.GetString("s_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save bootstrap.ini.
        /// </summary>
        internal static string save_bootstrap_ini {
            get {
                return ResourceManager.GetString("save_bootstrap_ini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select download folder.
        /// </summary>
        internal static string settings_select_dl_folder {
            get {
                return ResourceManager.GetString("settings_select_dl_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Issue.
        /// </summary>
        internal static string si {
            get {
                return ResourceManager.GetString("si", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have the right to write into this folder..
        /// </summary>
        internal static string si_message {
            get {
                return ResourceManager.GetString("si_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parallel installation with ease.
        /// </summary>
        internal static string siguislogan {
            get {
                return ResourceManager.GetString("siguislogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovenian.
        /// </summary>
        internal static string sl {
            get {
                return ResourceManager.GetString("sl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred! Message.
        /// </summary>
        internal static string standarderror {
            get {
                return ResourceManager.GetString("standarderror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start download.
        /// </summary>
        internal static string start_dl {
            get {
                return ResourceManager.GetString("start_dl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start installation.
        /// </summary>
        internal static string start_install {
            get {
                return ResourceManager.GetString("start_install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should the file be downloaded?.
        /// </summary>
        internal static string startdl {
            get {
                return ResourceManager.GetString("startdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should a sub folder be created automatically? Name of the sub folder.
        /// </summary>
        internal static string subfolder_do {
            get {
                return ResourceManager.GetString("subfolder_do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        internal static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File saved.
        /// </summary>
        internal static string title_filesave {
            get {
                return ResourceManager.GetString("title_filesave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkish.
        /// </summary>
        internal static string tr {
            get {
                return ResourceManager.GetString("tr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- Translations ---.
        /// </summary>
        internal static string translations {
            get {
                return ResourceManager.GetString("translations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translator.
        /// </summary>
        internal static string translator {
            get {
                return ResourceManager.GetString("translator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If enabled the files will be stored with their original filename.nIf disabled, only one installer and one help pack will be kept on the disk..
        /// </summary>
        internal static string tt_advanced_file {
            get {
                return ResourceManager.GetString("tt_advanced_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to manually check for updates? This will close the program!.
        /// </summary>
        internal static string tt_autoupdate {
            get {
                return ResourceManager.GetString("tt_autoupdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may use the following instead of the line starting with “UserInstallation=” from the text field above in order to not override your existing user profile..
        /// </summary>
        internal static string tt_bootstrap {
            get {
                return ResourceManager.GetString("tt_bootstrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SI GUI - Bootstrap.ini auto edited.
        /// </summary>
        internal static string tt_editbs_tit {
            get {
                return ResourceManager.GetString("tt_editbs_tit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bootstrap.ini file has been edited automatically. You can turn this off in the settings..
        /// </summary>
        internal static string tt_editbs_txt {
            get {
                return ResourceManager.GetString("tt_editbs_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install LibreOffice (not parallel).
        /// </summary>
        internal static string tt_go {
            get {
                return ResourceManager.GetString("tt_go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a desktop shortcut for this parallel installation.
        /// </summary>
        internal static string tt_ink {
            get {
                return ResourceManager.GetString("tt_ink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to the soffice.exe of the parallel installation (Automatically added).
        /// </summary>
        internal static string tt_path_to_exe {
            get {
                return ResourceManager.GetString("tt_path_to_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest testing build..
        /// </summary>
        internal static string tt_tb {
            get {
                return ResourceManager.GetString("tt_tb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language.
        /// </summary>
        internal static string update_lang {
            get {
                return ResourceManager.GetString("update_lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should %version really be downloaded?.
        /// </summary>
        internal static string versiondl {
            get {
                return ResourceManager.GetString("versiondl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        internal static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose installation directory.
        /// </summary>
        internal static string where_to_install {
            get {
                return ResourceManager.GetString("where_to_install", resourceCulture);
            }
        }
    }
}
